### PR TITLE
Add Chocolatey packaging back

### PR DESCRIPTION
**Pull request by fhunleth**
It seems like choco v0.10.16-beta fixed whatever broke with v0.10.15.

### CODE REVIEW

**Comment by michaelkschmidt** [comment]
Are you sure its worth maintaining Chocolatey at this point?  It almost seems like fwup should just download the fwup.exe version if it detects its in WSL

**Comment by fhunleth** [comment]
What do you mean? I thought Chocolatey was the package manager for Windows.

**Comment by michaelkschmidt** [comment]
Its a third party service, and has not reached widespread adoption.  WSL2 eliminates alot of need for it, and Microsoft has announced their own competitor (https://github.com/microsoft/winget-cli).   Also fwup.exe is standalone so its probably overkill packaging it up.

WSL2 is able to run .exe's directly from the Linux Filesystem, so we might consider just downloading the fwup.exe to ~/.fwup/ and invoke it if we need it.  I don't think there is anyone who uses it directly on Windows so it shouldn't break anyone.  They can always directly download fwup.exe as well if they need it.

**Comment by fhunleth** [comment]
`fwup` can't download anything so we'd have to add a script along side it. That seems pretty sketchy, imho, for a script to download a `.exe` file and run it.

I'd just point out that one of the purposes of using a package manager is to simplify update checks. On non-Windows platforms, `fwup` comes with a man page and helper scripts, so it's not really one `.exe` file. I think that given historic constraints on Windows that no one has bothered including the other files.

As for winget, I'm fine switching to it. I'm not sure what's involved. I think that either you or someone else from the community should manage it, though. I'm fine supporting issues, but I just don't have time to keep up to date with whatever the preferred methods are for people using a platform that I don't regularly use.

**Comment by michaelkschmidt** [comment]
That is a good point.  Another option is to create a fwup-wsl package and have it contain fwup-wsl.exe.

I don't know what the right solution is.  Each fwup package on Chocolately has only been downloaded ~200 times, so this is a lot of effort for something that really isn't used much.  That said WSL2 will probably increase the demand for it, we just need to figure out a better way to package it.

**Comment by fhunleth** [comment]
I'm not sure what to do with the popularity of fwup on Windows. The current Chocolately package is old, so I would suspect that some people have figured that out and ignored it. Also, it's pretty rare for Windows users to contribute back. Perhaps because there are so few of them, don't know. At any rate, I don't know what else to do. It certainly would be nice to have something for Windows.

If you don't want to do anything, that's fine. Perhaps someone else will pop up on this thread.

**Pull request merged**
