### PR TITLE
Add support for U-Boot redundant environment

### PR DESCRIPTION
**Pull request by davidepianca98**
This pull request adds support for U-Boot redundant environment maintaining compatibility with all the previous uboot commands for single environment.
The regression tests have been added, additionally uboot_setenv and require-uboot-variable have been tested on a real board

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks! And many thanks for adding the set of regression tests. That helps me a lot.

Overall it looks good. Let me take a closer pass this weekend or early next week when I have more time and I'll merge.

**Comment by davidepianca98** [comment]
No problem!
I would like to point out a few things:
- The regression tests all worked on my pc except four xdelta tests, while on travis-ci apparently various tests fail, I hope it's all ok, I didn't really look much into it
- Multiple uboot_setenv commands are not atomic, so one could have the update applied but only one of two U-Boot variables correctly updated if a power fail should happen exactly in between the setenv commands. I wonder if the correct way is adding an extra flag as last setenv command to indicate the update has been completed or if there should be a command with multiple variables to set, that sets them in RAM and then writes only once at the end

**Comment by fhunleth** [comment]
Wow, Travis is very unhappy. It was all green last week. Maybe you caught it at a bad time since I can't tell that your code did anything obviously wrong to make it fail like it did. As for the xdelta tests, they probably just fail since you don't have xdelta3 installed locally. Don't worry about that.

Regarding the unatomic uboot setenv commands, fwup's caching layer will combine them into two writes at the end (one for the first block and then one for the second one). `fwup`'s cache is organized in 128 KB blocks and it flushes blocks in the order that they were last written. Therefore if your last write in the conf file is to the uboot environment, then the blocks containing the uboot environment will be written last and second last. There's a `VERIFY_SYSCALLS_LAST_WRITE` environment variable that can be set in the regression tests to verify the last write syscall.

I'll look more later...

**Comment by davidepianca98** [comment]
Thank you very much, I didn't check the code for the cache and didn't know it worked like that.
Anyway installing xdelta3 did indeed make all the remaining tests pass.

**Comment by fhunleth** [comment]
FYI - All tests pass locally for me on Linux, but there's some regression on OSX. I don't see it in your PR. Given that Travis is showing odd errors without your change, I'd like to get to the bottom of that before merging.

I did make one change to spell out redundant in `uboot-offset-redundant` since I had been spelling words out in this project. See commit https://github.com/fhunleth/fwup/commit/3f9087459ff943e0d21e9716b7d971bbf87b4db8.

**Comment by fhunleth** [comment]
Update - it turns out that there was no regression. I messed up what I thought was a trivial valgrind memory leak fix. Travis reports success across the board. As part of checking everything with valgrind, I fixed very minor issues in fwup that don't affect anything. There was a memory leak reported for this branch. I haven't dug into that yet. There are also uninitialized accesses being reported in libconfuse and fatfs. The libconfuse one is triggered by whitespace removal in comments, so it tends to obscure things if you look into this.

**Comment by davidepianca98** [comment]
Should I have a look at the reported memory leak and other warnings?

**Comment by fhunleth** [comment]
Yes, could you? As far as I can tell, the libconfuse and fatfs issues that valgrind found don't result in anything noticeable, and I heard back from the libconfuse maintainer that he'd be issuing a new release soon anyway (it was fixed in libconfuse master months ago).

I'm working on this PR on a best-effort basis which means that I'll be regularly taking passes at pushing it forward every 1-2 weeks as time permits. I'll get there. I just wanted to confirm that nothing else could be causing the CI failures and I hadn't run valgrind in a really long time.

**Comment by davidepianca98** [comment]
Sorry for the late reply. I ran the valgrind tests and fixed the bugs related to this pull request code. The failing tests are the same that are failing on the master branch, plus test 185 which fails because of libconfuse, so I left it there for now.

**Comment by fhunleth** [comment]
Thanks!

I've been trying it out and I see how it works now. It seems to work well for me.

I also better understand your comment earlier about multiple setenv's not being atomic. `fwup`'s caching system does indeed coalesce the multiple setenv's into one write, but this does not address the ping/pong writes that `fw_setenv` does. So multiple setenv's will end up writing both environments in one call to `fwup`, whereas one call to `fw_setenv` will only update one environment block no matter how many variables are set at a time. I can see how this would be non-ideal.

I have a pass at a commit that refactors the PR to centralize the handling of the read and write logic that ended up having to be added to every uboot_* function. Thanks to your unit tests, this wasn't hard at all. Unless something blows up at work tomorrow, I expect to finish up and merge this by Tuesday and get a release out.

Thanks again!

**Comment by fhunleth** [comment]
Merged! Thanks!

**Comment by davidepianca98** [comment]
Thank you for taking the time to rewrite the code in a way that better matches the codebase, I'm going to try this on a board very soon

**Comment by fhunleth** [comment]
@davidepianca98 Did you get a chance to try it out? I'm ready to make a release, but I figured that it would be sensible to wait for you first.

Also, if you can share it, what processor or board are you using `fwup` with?

**Comment by davidepianca98** [comment]
I tried it just now and it looks like it works well for my application. As I said earlier it only uses uboot_setenv and require-uboot-variable though. The board is a beaglebone black based custom board.

**Comment by fhunleth** [comment]
Thanks for testing! The release should be out shortly.

**Pull request merged**
