### PR TITLE
Using off_t to prevent problems with large files and offsets

### PR DESCRIPTION
**Pull request by edahlseng**

### CODE REVIEW

**Comment by fhunleth** [comment]
Cool! From my brief scan, it looks pretty good. This change makes long file size support mandatory, but I'm ok with that. Buildroot just deprecated non-LFS support, and I can't think of any other systems that still support it. It might be worth a quick comment in the Makefile.am stating that LFS support is required, though. It would also be nice to have a unit test to verify that >2GB files work. However, I'm not sure if that will work on Travis, so I'll merge this without a unit test if it turns out to be non-trivial. In any case, I'll take a longer look through the diff this evening or tomorrow so that we can get this merged. 

Thank you very much for fixing this!!

**Comment by edahlseng** [comment]
Awesome!  I was trying to find a way for LFS to be optional, but my experience with automake is limited, and the only way I could get it to work was to explicitly add in the build flag. If there was an easy way to make it optional, or even enabled by default but have the ability to easily disable it, I think that would be good!  It would probably also be good to add a unit test for files > 4GiB files.  Since there were several places that used unsigned ints (particularly size_t), there could be cases where files greater than 2 GiB work, but not greater than 4.  If you the unit tests end up being more involved, let me know and I can try to get something added by the end of this week!

**Comment by fhunleth** [comment]
I added some unit tests for large offsets and large FAT partition sizes in the https://github.com/fhunleth/fwup/tree/lfs branch. I haven't added tests for >4GiB files, since that didn't work and I haven't looked into why. Could you see if there are any other unit tests that would be good to add for this feature?

**Comment by edahlseng** [comment]
The only other test that I can think of is writing a large file.  I'm going to be out of town for the next week, and I won't be able to look at that while I'm gone, but if you don't have a chance I can look into it when I get back.

**Comment by fhunleth** [comment]
I merged it without the large file since the patch was useful regardless. Thanks again for taking the time to make the changes and send them over.

**Pull request merged**
