### PR TITLE
Added fwup wrapper script

### PR DESCRIPTION
**Pull request by jmerriweather**
This should add fwup to the chocolatey package

### CODE REVIEW

**Comment by fhunleth** [comment]
Looks good to me! @michaelkschmidt?

**Comment by jmerriweather** [comment]
Actually this will put the fwup wrapper into tools directory not the bin directory

**Comment by jmerriweather** [comment]
So had more of a look into this, chocolatey automatically shims exe and bat files into the bin directory. I think we'll need to use Install-BinFile to add the extensionless fwup file into the bin directory.

**Comment by jmerriweather** [comment]
Looking through the source of chocolatey it might actually shim the bash file. Might need someone with more experience with making chocolatey packages.

**Comment by michaelkschmidt** [comment]
@fhunleth @jmerriweather I think I need to deep dive on this.  There is some "automagic" going on with windows mapping "fwup" -> "fwup.exe"

```
PS C:\ProgramData\Chocolatey\bin> dir fwup*


    Directory: C:\ProgramData\Chocolatey\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         8/1/2017  12:30 PM          26112 fwup.exe

PS C:\ProgramData\Chocolatey\bin> vim.exe fwup
(vim opens fwup.exe)
```

This will make adding the shell script next to the .exe a little tricky.  We might have to resort to putting the shell script in bin, and have it call the exe in tools.

**Comment by fhunleth** [comment]
Ugh! I had no idea this would end up being complicated!

Timing-wise, I'm planning a new `fwup` release this weekend since some enhancements to the firmware signing feature are needed on another project. I don't know how much work is left to get this PR in, but it would be cool to get it in as well. If that's not feasible, though, don't worry about it.

**Comment by fhunleth** [comment]
Closed - see #70.

**Pull request closed without merging**
